import cv2
image = cv2.imread("stranger-things.jpg")
gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
cv2.imshow("Grayscaledd", gray)
cv2.waitKey(0)
bgr = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
cv2.imshow("BGR", bgr)
cv2.waitKey(0)
hls = cv2.cvtColor(image, cv2.COLOR_RGB2HLS)
cv2.imshow("HLS", hls)
cv2.waitKey(0)
hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
cv2.imshow("HSV", hsv)
cv2.waitKey(0)
lab = cv2.cvtColor(image, cv2.COLOR_RGB2LAB)
cv2.imshow("LAB", lab)
cv2.waitKey(0)
luv = cv2.cvtColor(image, cv2.COLOR_RGB2LUV)
cv2.imshow("Luv", luv)
cv2.waitKey(0)
xyz = cv2.cvtColor(image, cv2.COLOR_RGB2XYZ)
cv2.imshow("XYZ", xyz)
cv2.waitKey(0)